MMS_NH3_EF:
  dairy_cattle:
    slurry:
      housing: 0.24
      yard: 0.30
      storage: 0.25
      application: 0.55
      grazing: 0.14
    solid:
      housing: 0.08
      yard: 0.30
      storage: 0.32
      application: 0.68
      grazing: 0.14

  dairy_cattle_tied:
    slurry:
      housing: 0.09
      yard: 0.30
      storage: 0.25
      application: 0.55
      grazing: 0.14
    solid:
      housing: 0.09
      yard: 0.30
      storage: 0.32
      application: 0.68
      grazing: 0.14

  cattle:
    slurry:
      housing: 0.24
      yard: 0.53
      storage: 0.25
      application: 0.55
      grazing: 0.14
    solid:
      housing: 0.08
      yard: 0.53
      storage: 0.32
      application: 0.68
      grazing: 0.14

  sheep:
    solid:
      housing: 0.22
      yard: 0.75
      storage: 0.32
      application: 0.90
      grazing: 0.09

  pigs:
    slurry:
      housing: 0.27
      yard: 0.53
      storage: 0.11
      application: 0.40
    solid:
      housing: 0.23
      yard: 0.53
      storage: 0.29
      application: 0.45

  piglets:
    slurry:
      housing: 0.35
      yard: null
      storage: 0.11
      application: 0.29
    solid:
      housing: 0.24
      yard: null
      storage: 0.29
      application: 0.45

  sows:
    slurry:
      housing: 0.35
      yard: null
      storage: 0.11
      application: 0.29
    solid:
      housing: 0.24
      yard: null
      storage: 0.29
      application: 0.45

  goats:
    solid:
      housing: 0.22
      yard: 0.75
      storage: 0.28
      application: 0.90
      grazing: 0.09

  horses:
    solid:
      housing: 0.22
      yard: null
      storage: 0.35
      application: 0.90
      grazing: 0.35

laying_hens:
    solid:
      housing: 0.20
      yard: null
      storage: 0.08
      application: 0.45
    slurry:
      housing: 0.41
      yard: null
      storage: 0.14
      application: 0.69

  broilers:
    solid:
      housing: 0.21
      yard: null
      storage: 0.30
      application: 0.38

  turkeys:
    solid:
      housing: 0.35
      yard: null
      storage: 0.24
      application: 0.54

  ducks:
    solid:
      housing: 0.24
      yard: null
      storage: 0.24
      application: 0.54

  geese:
    solid:
      housing: 0.57
      yard: null
      storage: 0.16
      application: 0.45

  fur_animals:
    solid:
      housing: 0.27
      yard: null
      storage: 0.09
      application: 0.31